[
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या आप सेवा में उपस्थित थे?",
    response: "Yes",
    comment: "",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या आज टॉयलेट साफ था?",
    response: "No",
    comment: "honey",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या आज टॉयलेट में पानी की व्यवस्था थी?",
    response: "No",
    comment: "honey",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या आज टॉयलेट में दुर्गंध नहीं थी और फ्रेशनर का उपयोग किया गया था?",
    response: "No",
    comment: "honey",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या आज नल, फ्लश और वॉशबेसिन सही स्थिति में थे?",
    response: "No",
    comment: "honey",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या आज टॉयलेट के दरवाज़े ठीक से बंद हो रहे थे और सुरक्षित थे?",
    response: "Yes",
    comment: "",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या टॉयलेट पूरी तरह गंदे कपड़ों से मुक्त था?",
    response: "No",
    comment: "",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या आज बाल्टी मौजूद थी और साफ थी?",
    response: "Yes",
    comment: "",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या लीकेज पूरी तरह से ठीक है?",
    response: "Yes",
    comment: "",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "क्या टॉयलेट में फर्श साफ और सूखा था?",
    response: "Yes",
    comment: "",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Toilet - Evening",
    task: "4 बाल्टियाँ और 4 मग हैं क्या?",
    response: "Yes",
    comment: "",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Basement Evening",
    task: "क्या आप सेवा में उपस्थित थे?",
    response: "Yes",
    comment: "",
  },
  {
    devoteeName: "Balwan Hari Prabhuji",
    serviceName: "Basement Evening",
    task: "क्या बेसमेंट साफ़ है?",
    response: "No",
    comment: "",
  },
];
